--
--Необходимо прогнать данный скрипт для компиляции всех объектов, неоткомпилированных после восстановления базы
-- прогонять нужно только под правами роли SYSDBA
--https://docs.oracle.com/cd/B28359_01/appdev.111/b28419/u_recomp.htm#i1000051
--



    GRANT EXECUTE ON SYS.DBMS_CHANGE_NOTIFICATION TO SOLUTION_MED;
    GRANT EXECUTE ON SYS.DBMS_LOCK TO SOLUTION_MED;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO SOLUTION_MED;
    GRANT SELECT ON SYS.V_$DATABASE TO SOLUTION_MED;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_MED;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_MED;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_MED;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_DATA;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_DATA;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_DATA;
    GRANT SELECT ON SYS.V_$SESSION TO IMPEX;
    GRANT SELECT ON SYS.V_$SESSTAT TO IMPEX;
    GRANT SELECT ON SYS.V_$STATNAME TO IMPEX;
    GRANT SELECT ON SYS.V_$SESSION TO INETUSER;
    GRANT SELECT ON SYS.V_$SESSTAT TO INETUSER;
    GRANT SELECT ON SYS.V_$STATNAME TO INETUSER;
    GRANT SELECT ON SYS.V_$SESSION TO INFIS;
    GRANT SELECT ON SYS.V_$SESSTAT TO INFIS;
    GRANT SELECT ON SYS.V_$STATNAME TO INFIS;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_AGRDEP;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_AGRDEP;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_AGRDEP;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_APTEKA;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_APTEKA;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_APTEKA;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_DBF;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_DBF;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_DBF;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_DIAGNOSTIC;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_DIAGNOSTIC;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_DIAGNOSTIC;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_DIET;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_DIET;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_DIET;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_EPIC;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_EPIC;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_EPIC;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_ER;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_ER;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_ER;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_FORM;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_FORM;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_FORM;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_KLADR;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_KLADR;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_KLADR;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_LAB;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_LAB;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_LAB;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_LOG;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_LOG;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_LOG;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_OPK;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_OPK;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_OPK;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_PACS;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_PACS;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_PACS;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_REAGENT;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_REAGENT;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_REAGENT;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_REG;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_REG;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_REG;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_RIGHTS;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_RIGHTS;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_RIGHTS;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_SOI;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_SOI;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_SOI;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_STORAGE;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_STORAGE;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_STORAGE;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_STORAGE_BUILD;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_STORAGE_BUILD;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_STORAGE_BUILD;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_TMP;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_TMP;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_TMP;
    GRANT SELECT ON SYS.V_$SESSION TO SOLUTION_VAC;
    GRANT SELECT ON SYS.V_$SESSTAT TO SOLUTION_VAC;
    GRANT SELECT ON SYS.V_$STATNAME TO SOLUTION_VAC;

    begin
        UTL_RECOMP.RECOMP_SERIAL();
    end;
