--
-- Необходимо прогнать данный скрипт перед импортом базы заменив пути на актуальные                     : 
--

CREATE TABLESPACE DATA DATAFILE 
  'D:\DATAFILES\MEDTEST\DATATBS00.DBF' SIZE 17740M AUTOEXTEND ON NEXT 2500M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\DATATBS02.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\DATATBS03.DBF' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE DATA_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\DATAIDXTBS00.DBF' SIZE 5G AUTOEXTEND ON NEXT 1250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE DIAGNOSTIC DATAFILE 
  'D:\DATAFILES\MEDTEST\DIAGNOSTICTBS00.DBF' SIZE 2000M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE DIAGNOSTIC_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\DIAGNOSTICIDXTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE EPIC DATAFILE 
  'D:\DATAFILES\MEDTEST\EPICTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE EPIC_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\EPICIDXTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE FIN DATAFILE 
  'D:\DATAFILES\MEDTEST\FINTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE FIN_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\FINIDXTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE IMPEX DATAFILE 
  'D:\DATAFILES\MEDTEST\IMPEXTBS00.DBF' SIZE 5G AUTOEXTEND ON NEXT 1250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE IMPEX_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\IMPEXIDXTBS00.DBF' SIZE 2500M AUTOEXTEND ON NEXT 625M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE INFIS DATAFILE 
  'D:\DATAFILES\MEDTEST\INFISTBS00.DBF' SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE INFIS_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\INFISIDXTBS00.DBF' SIZE 100M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE KLADR DATAFILE 
  'D:\DATAFILES\MEDTEST\KLADRTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE KLADR_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\KLADRIDXTBS00.DBF' SIZE 125M AUTOEXTEND ON NEXT 31M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LAB DATAFILE 
  'D:\DATAFILES\MEDTEST\LABTBS00.DBF' SIZE 2000M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LAB_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\LABIDXTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LOG DATAFILE 
  'D:\DATAFILES\MEDTEST\LOGTBS00.DBF' SIZE 17740M AUTOEXTEND ON NEXT 2500M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGTBS02.DBF' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGTBS03.DBF' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGTBS04.DBF' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LOG_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\LOGIDXTBS00.DBF' SIZE 26370M AUTOEXTEND ON NEXT 1250M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGIDXTBS02.DBF' SIZE 2274M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGIDXTBS03.DBF' SIZE 1274M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE MED DATAFILE 
  'D:\DATAFILES\MEDTEST\MEDTESTTBS00.DBF' SIZE 12G AUTOEXTEND ON NEXT 3G MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE MED_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\MEDTESTIDXTBS00.DBF' SIZE 6G AUTOEXTEND ON NEXT 1500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PACS DATAFILE 
  'D:\DATAFILES\MEDTEST\PACSTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PACS_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\PACSIDXTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE REG DATAFILE 
  'D:\DATAFILES\MEDTEST\REGTBS00.DBF' SIZE 4000M AUTOEXTEND ON NEXT 1000M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE REG_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\REGIDXTBS00.DBF' SIZE 2000M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SOI DATAFILE 
  'D:\DATAFILES\MEDTEST\SOITBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\SOITBS02.DBF' SIZE 550M AUTOEXTEND ON NEXT 137M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SOI_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\SOIIDXTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE STOR DATAFILE 
  'D:\DATAFILES\MEDTEST\STORTBS00.DBF' SIZE 2000M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE STOR_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\STORIDXTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SYSAUX DATAFILE 
  'D:\DATAFILES\MEDTEST\SYSAUX01.DBF' SIZE 1310M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SYSTEM DATAFILE 
  'D:\DATAFILES\MEDTEST\SYSTEM01.DBF' SIZE 5070M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
  'D:\DATAFILES\MEDTEST\TEMP01.DBF' SIZE 32767M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE TABLESPACE TMPTS DATAFILE 
  'D:\DATAFILES\MEDTEST\TMPTSTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE TMPTS_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\TMPTSIDXTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE UNDO TABLESPACE UNDOTBS1 DATAFILE 
  'D:\DATAFILES\MEDTEST\UNDOTBS01.DBF' SIZE 18725M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
ONLINE
RETENTION NOGUARANTEE
BLOCKSIZE 8K
FLASHBACK ON;


CREATE TABLESPACE USERS DATAFILE 
  'D:\DATAFILES\MEDTEST\USERS01.DBF' SIZE 5M AUTOEXTEND ON NEXT 1280K MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE VAC DATAFILE 
  'D:\DATAFILES\MEDTEST\VACTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE VAC_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\VACIDXTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE DIRECTORY IMPORT AS 'C:\IMPORT'