--
-- Необходимо прогнать данный скрипт перед импортом базы заменив пути на актуальные                     : 
--

CREATE TABLESPACE DATA DATAFILE 
  'D:\DATAFILES\MEDTEST\DATATBS00.DBF' SIZE 17740M AUTOEXTEND ON NEXT 2500M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\DATATBS02.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\DATATBS03.DBF' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE DATA_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\DATAIDXTBS00.DBF' SIZE 5G AUTOEXTEND ON NEXT 1250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE DIAGNOSTIC DATAFILE 
  'D:\DATAFILES\MEDTEST\DIAGNOSTICTBS00.DBF' SIZE 2000M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE DIAGNOSTIC_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\DIAGNOSTICIDXTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE EPIC DATAFILE 
  'D:\DATAFILES\MEDTEST\EPICTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE EPIC_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\EPICIDXTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE FIN DATAFILE 
  'D:\DATAFILES\MEDTEST\FINTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE FIN_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\FINIDXTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE IMPEX DATAFILE 
  'D:\DATAFILES\MEDTEST\IMPEXTBS00.DBF' SIZE 5G AUTOEXTEND ON NEXT 1250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE IMPEX_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\IMPEXIDXTBS00.DBF' SIZE 2500M AUTOEXTEND ON NEXT 625M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE INFIS DATAFILE 
  'D:\DATAFILES\MEDTEST\INFISTBS00.DBF' SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE INFIS_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\INFISIDXTBS00.DBF' SIZE 100M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE KLADR DATAFILE 
  'D:\DATAFILES\MEDTEST\KLADRTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE KLADR_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\KLADRIDXTBS00.DBF' SIZE 125M AUTOEXTEND ON NEXT 31M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LAB DATAFILE 
  'D:\DATAFILES\MEDTEST\LABTBS00.DBF' SIZE 2000M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LAB_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\LABIDXTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LOG DATAFILE 
  'D:\DATAFILES\MEDTEST\LOGTBS00.DBF' SIZE 17740M AUTOEXTEND ON NEXT 2500M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGTBS02.DBF' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGTBS03.DBF' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGTBS04.DBF' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LOG_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\LOGIDXTBS00.DBF' SIZE 26370M AUTOEXTEND ON NEXT 1250M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGIDXTBS02.DBF' SIZE 2274M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\LOGIDXTBS03.DBF' SIZE 1274M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE MED DATAFILE 
  'D:\DATAFILES\MEDTEST\MEDTESTTBS00.DBF' SIZE 12G AUTOEXTEND ON NEXT 3G MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE MED_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\MEDTESTIDXTBS00.DBF' SIZE 6G AUTOEXTEND ON NEXT 1500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PACS DATAFILE 
  'D:\DATAFILES\MEDTEST\PACSTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PACS_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\PACSIDXTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE REG DATAFILE 
  'D:\DATAFILES\MEDTEST\REGTBS00.DBF' SIZE 4000M AUTOEXTEND ON NEXT 1000M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE REG_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\REGIDXTBS00.DBF' SIZE 2000M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SOI DATAFILE 
  'D:\DATAFILES\MEDTEST\SOITBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED,
  'D:\DATAFILES\MEDTEST\SOITBS02.DBF' SIZE 550M AUTOEXTEND ON NEXT 137M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SOI_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\SOIIDXTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE STOR DATAFILE 
  'D:\DATAFILES\MEDTEST\STORTBS00.DBF' SIZE 2000M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE STOR_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\STORIDXTBS00.DBF' SIZE 1000M AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SYSAUX DATAFILE 
  'D:\DATAFILES\MEDTEST\SYSAUX01.DBF' SIZE 1310M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SYSTEM DATAFILE 
  'D:\DATAFILES\MEDTEST\SYSTEM01.DBF' SIZE 5070M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
  'D:\DATAFILES\MEDTEST\TEMP01.DBF' SIZE 32767M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE TABLESPACE TMPTS DATAFILE 
  'D:\DATAFILES\MEDTEST\TMPTSTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE TMPTS_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\TMPTSIDXTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE UNDO TABLESPACE UNDOTBS1 DATAFILE 
  'D:\DATAFILES\MEDTEST\UNDOTBS01.DBF' SIZE 18725M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
ONLINE
RETENTION NOGUARANTEE
BLOCKSIZE 8K
FLASHBACK ON;


CREATE TABLESPACE USERS DATAFILE 
  'D:\DATAFILES\MEDTEST\USERS01.DBF' SIZE 5M AUTOEXTEND ON NEXT 1280K MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE VAC DATAFILE 
  'D:\DATAFILES\MEDTEST\VACTBS00.DBF' SIZE 500M AUTOEXTEND ON NEXT 125M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE VAC_IDX DATAFILE 
  'D:\DATAFILES\MEDTEST\VACIDXTBS00.DBF' SIZE 250M AUTOEXTEND ON NEXT 62M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE USER ANONYMOUS
  IDENTIFIED BY VALUES 'anonymous'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for ANONYMOUS 
  GRANT CREATE SESSION TO ANONYMOUS;


CREATE USER APEX_PUBLIC_USER
  IDENTIFIED BY VALUES 'S:32539BC9A3CA03B9ABE2816E8E81F54BE23672E98CD7A0BF2DB4AE2435F1;0DDCD4ABDE3F1E8A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for APEX_PUBLIC_USER 
  GRANT CREATE SESSION TO APEX_PUBLIC_USER;


CREATE USER APEX_030200
  IDENTIFIED BY VALUES 'S:B03F84ED7D58D3FC1FFC5E9DA570ACD2C5BDA83BAE77FE24B615747AD9B5;FA0D918FD325FEDB'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for APEX_030200 
  GRANT CONNECT TO APEX_030200 WITH ADMIN OPTION;
  GRANT RESOURCE TO APEX_030200 WITH ADMIN OPTION;
  ALTER USER APEX_030200 DEFAULT ROLE ALL;
  -- 26 System Privileges for APEX_030200 
  GRANT ALTER DATABASE TO APEX_030200;
  GRANT ALTER SESSION TO APEX_030200;
  GRANT ALTER SYSTEM TO APEX_030200;
  GRANT ALTER USER TO APEX_030200;
  GRANT CREATE ANY CONTEXT TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE CLUSTER TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE DIMENSION TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE INDEXTYPE TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE JOB TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE MATERIALIZED VIEW TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE OPERATOR TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE PROCEDURE TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE PUBLIC SYNONYM TO APEX_030200;
  GRANT CREATE ROLE TO APEX_030200;
  GRANT CREATE SEQUENCE TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE SYNONYM TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE TABLE TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE TABLESPACE TO APEX_030200;
  GRANT CREATE TRIGGER TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE TYPE TO APEX_030200 WITH ADMIN OPTION;
  GRANT CREATE USER TO APEX_030200;
  GRANT CREATE VIEW TO APEX_030200 WITH ADMIN OPTION;
  GRANT DROP PUBLIC SYNONYM TO APEX_030200;
  GRANT DROP TABLESPACE TO APEX_030200;
  GRANT DROP USER TO APEX_030200;
  GRANT UNLIMITED TABLESPACE TO APEX_030200 WITH ADMIN OPTION;


CREATE USER APPQOSSYS
  IDENTIFIED BY VALUES 'S:ACA0B5C8278AE574A6BAB080B2328576598E44206B9E120E005629FCE08E;519D632B7EE7F63A'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 3 System Privileges for APPQOSSYS 
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'APPQOSSYS', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
  GRANT ALTER SESSION TO APPQOSSYS;
  GRANT CREATE SESSION TO APPQOSSYS;
  -- 1 Tablespace Quota for APPQOSSYS 
  ALTER USER APPQOSSYS QUOTA UNLIMITED ON SYSAUX;


CREATE USER CTXSYS
  IDENTIFIED BY VALUES 'S:460984F19CC9033E4383C4EF21ECC6236096D3F499AE581E796A5A07807C;D1D21CA56994CAB6'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for CTXSYS 
  GRANT CTXAPP TO CTXSYS WITH ADMIN OPTION;
  GRANT RESOURCE TO CTXSYS;
  ALTER USER CTXSYS DEFAULT ROLE ALL;
  -- 9 System Privileges for CTXSYS 
  GRANT ALTER SESSION TO CTXSYS;
  GRANT CREATE JOB TO CTXSYS;
  GRANT CREATE PUBLIC SYNONYM TO CTXSYS;
  GRANT CREATE SESSION TO CTXSYS;
  GRANT CREATE SYNONYM TO CTXSYS;
  GRANT CREATE VIEW TO CTXSYS;
  GRANT DROP PUBLIC SYNONYM TO CTXSYS;
  GRANT MANAGE SCHEDULER TO CTXSYS;
  GRANT UNLIMITED TABLESPACE TO CTXSYS;


CREATE USER DBSNMP
  IDENTIFIED BY VALUES 'S:BD00795124C622421C75E6DC4E5D3C41C5C567CE86432A9DB8C5CE913C5E;FFF45BB2C0C327EC'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE MONITORING_PROFILE
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;
  -- 1 Role for DBSNMP 
  GRANT OEM_MONITOR TO DBSNMP;
  ALTER USER DBSNMP DEFAULT ROLE ALL;
  -- 4 System Privileges for DBSNMP 
  GRANT CREATE PROCEDURE TO DBSNMP;
  GRANT CREATE TABLE TO DBSNMP;
  GRANT SELECT ANY DICTIONARY TO DBSNMP;
  GRANT UNLIMITED TABLESPACE TO DBSNMP;


CREATE USER DIP
  IDENTIFIED BY VALUES 'S:5D61BE394B76C363170B9980263415182657CA2BA3CB4727A32B323CDF9C;CE4A36B8E06CA59C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for DIP 
  GRANT CREATE SESSION TO DIP;


CREATE USER EXFSYS
  IDENTIFIED BY VALUES 'S:5A53535C54DD04533A5D3276275182B4849259BD201E5BCCEDE1E04382CD;33C758A8E388DEE5'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 Role for EXFSYS 
  GRANT RESOURCE TO EXFSYS;
  ALTER USER EXFSYS DEFAULT ROLE ALL;
  -- 9 System Privileges for EXFSYS 
  GRANT ADMINISTER DATABASE TRIGGER TO EXFSYS;
  GRANT CREATE ANY TRIGGER TO EXFSYS;
  GRANT CREATE INDEXTYPE TO EXFSYS;
  GRANT CREATE JOB TO EXFSYS;
  GRANT CREATE LIBRARY TO EXFSYS;
  GRANT CREATE OPERATOR TO EXFSYS;
  GRANT CREATE SESSION TO EXFSYS;
  GRANT MANAGE SCHEDULER TO EXFSYS;
  GRANT UNLIMITED TABLESPACE TO EXFSYS;


CREATE USER FLOWS_FILES
  IDENTIFIED BY VALUES 'S:2021AF95B68C51BC6FFB4333E946CC69604837A01EEC342B7518C942E69F;B93DC681A4ED561C'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for FLOWS_FILES 
  GRANT CREATE SYNONYM TO FLOWS_FILES;
  -- 1 Tablespace Quota for FLOWS_FILES 
  ALTER USER FLOWS_FILES QUOTA UNLIMITED ON SYSAUX;


CREATE USER IMPEX
  IDENTIFIED BY VALUES 'S:68135C8C8695772F5A7A1C667CD61F21FF3E230F7D2D39F8E058426D8A77;E70D1F681333D667'
  DEFAULT TABLESPACE IMPEX
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for IMPEX 
  GRANT CONNECT TO IMPEX;
  GRANT RESOURCE TO IMPEX;
  ALTER USER IMPEX DEFAULT ROLE ALL;
  -- 9 System Privileges for IMPEX 
  GRANT CREATE ANY TRIGGER TO IMPEX;
  GRANT CREATE PROCEDURE TO IMPEX;
  GRANT CREATE VIEW TO IMPEX;
  GRANT DELETE ANY TABLE TO IMPEX;
  GRANT EXECUTE ANY PROCEDURE TO IMPEX;
  GRANT INSERT ANY TABLE TO IMPEX;
  GRANT SELECT ANY TABLE TO IMPEX;
  GRANT UNLIMITED TABLESPACE TO IMPEX WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO IMPEX;


CREATE USER INETUSER
  IDENTIFIED BY VALUES 'S:7798F508EB5CFC2A08FB238FECD2719C4AED3B1104DC00E02064AC31259C;9790650ADED0E11A'
  DEFAULT TABLESPACE MED
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for INETUSER 
  GRANT CONNECT TO INETUSER;
  GRANT RESOURCE TO INETUSER;
  ALTER USER INETUSER DEFAULT ROLE ALL;
  -- 2 System Privileges for INETUSER 
  GRANT CREATE VIEW TO INETUSER;
  GRANT UNLIMITED TABLESPACE TO INETUSER;


CREATE USER INFIS
  IDENTIFIED BY VALUES 'S:B4149E4FACA6DDE1CCDE6A64CBABE421F1C30C1F10064D18CF5B98FE4E13;4FF952A82F8F92E6'
  DEFAULT TABLESPACE INFIS
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for INFIS 
  GRANT CONNECT TO INFIS;
  GRANT RESOURCE TO INFIS;
  ALTER USER INFIS DEFAULT ROLE ALL;
  -- 2 System Privileges for INFIS 
  GRANT CREATE VIEW TO INFIS;
  GRANT UNLIMITED TABLESPACE TO INFIS;


CREATE USER ITADMIN
  IDENTIFIED BY VALUES 'S:B5227470F06D0FE4BE9543A81B7EA4771616314727057BE81D77446C010F;5014DA3BC3B2C8A0'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for ITADMIN 
  GRANT DBA TO ITADMIN;
  ALTER USER ITADMIN DEFAULT ROLE ALL;
  -- 1 System Privilege for ITADMIN 
  GRANT UNLIMITED TABLESPACE TO ITADMIN;


CREATE USER MDDATA
  IDENTIFIED BY VALUES 'S:9FC42A5993E26C70FC431224E13AE285476941B1A3232E29BD02B415F7A7;DF02A496267DEE66'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for MDDATA 
  GRANT CONNECT TO MDDATA;
  GRANT RESOURCE TO MDDATA;
  ALTER USER MDDATA DEFAULT ROLE ALL;
  -- 1 System Privilege for MDDATA 
  GRANT UNLIMITED TABLESPACE TO MDDATA;


CREATE USER MDSYS
  IDENTIFIED BY VALUES 'S:AA499977319DA9F3C7E5A7F2C2FD76D884246205329EA0763C4EDA23B71B;72979A94BAD2AF80'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for MDSYS 
  GRANT CONNECT TO MDSYS;
  GRANT RESOURCE TO MDSYS;
  ALTER USER MDSYS DEFAULT ROLE ALL;
  -- 20 System Privileges for MDSYS 
  GRANT ADMINISTER DATABASE TRIGGER TO MDSYS;
  GRANT ALTER ANY TABLE TO MDSYS;
  GRANT CREATE ANY TRIGGER TO MDSYS;
  GRANT CREATE INDEXTYPE TO MDSYS;
  GRANT CREATE LIBRARY TO MDSYS;
  GRANT CREATE OPERATOR TO MDSYS;
  GRANT CREATE PROCEDURE TO MDSYS;
  GRANT CREATE PUBLIC SYNONYM TO MDSYS;
  GRANT CREATE SEQUENCE TO MDSYS;
  GRANT CREATE SESSION TO MDSYS;
  GRANT CREATE TABLE TO MDSYS;
  GRANT CREATE TYPE TO MDSYS;
  GRANT CREATE VIEW TO MDSYS;
  GRANT DELETE ANY TABLE TO MDSYS;
  GRANT DROP ANY TRIGGER TO MDSYS;
  GRANT DROP PUBLIC SYNONYM TO MDSYS;
  GRANT FLASHBACK ANY TABLE TO MDSYS;
  GRANT SELECT ANY TABLE TO MDSYS;
  GRANT UNLIMITED TABLESPACE TO MDSYS;
  GRANT UPDATE ANY TABLE TO MDSYS;
  -- 5 Java Privileges for MDSYS 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'md/jlib/*'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
  SYS.DBMS_JAVA.DISABLE_PERMISSION
    (key => KEYNUM);
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'sdo/demo/georaster/jlibs/*'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
  SYS.DBMS_JAVA.DISABLE_PERMISSION
    (key => KEYNUM);
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'md\jlib\*'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'sdo\demo\georaster\jlibs\*'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'MDSYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'getClassLoader'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/


CREATE USER MGMT_VIEW
  IDENTIFIED BY VALUES 'S:7067494C849528DFD6082A4D4C7667237E19A03D80FEF1C42451D0070421;A3431556B73F6AAD'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for MGMT_VIEW 
  GRANT MGMT_USER TO MGMT_VIEW;
  ALTER USER MGMT_VIEW DEFAULT ROLE ALL;


CREATE USER OLAPSYS
  IDENTIFIED BY VALUES 'S:673E22C5D8FDE902CA1CA37690B7B160975876049557A3524CFE7E87D3B0;4AC23CC3B15E2208'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for OLAPSYS 
  GRANT OLAP_DBA TO OLAPSYS;
  GRANT RESOURCE TO OLAPSYS;
  ALTER USER OLAPSYS DEFAULT ROLE ALL;
  -- 13 System Privileges for OLAPSYS 
  GRANT CREATE ANY DIMENSION TO OLAPSYS;
  GRANT CREATE ANY SYNONYM TO OLAPSYS;
  GRANT CREATE PROCEDURE TO OLAPSYS;
  GRANT CREATE PUBLIC SYNONYM TO OLAPSYS;
  GRANT CREATE SEQUENCE TO OLAPSYS;
  GRANT CREATE TABLE TO OLAPSYS;
  GRANT CREATE VIEW TO OLAPSYS;
  GRANT DROP ANY DIMENSION TO OLAPSYS;
  GRANT DROP ANY SYNONYM TO OLAPSYS;
  GRANT DROP PUBLIC SYNONYM TO OLAPSYS;
  GRANT SELECT ANY DICTIONARY TO OLAPSYS;
  GRANT SELECT ANY TABLE TO OLAPSYS;
  GRANT UNLIMITED TABLESPACE TO OLAPSYS;
  -- 1 Tablespace Quota for OLAPSYS 
  ALTER USER OLAPSYS QUOTA UNLIMITED ON SYSAUX;


CREATE USER ORACLE_OCM
  IDENTIFIED BY VALUES 'S:0E15CA7472B0A08F13BFAA8FA89D7A70B4D25B440341E2441310C9AD3BC1;5A2E026A9157958C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for ORACLE_OCM 
  GRANT CREATE JOB TO ORACLE_OCM;


CREATE USER ORDDATA
  IDENTIFIED BY VALUES 'S:D0830E7A2F1CD5D6AAF3979AE954BF4C52B51D4032F4AA9D272716BA8F49;A93EC937FCD1DC2A'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for ORDDATA 
  GRANT UNLIMITED TABLESPACE TO ORDDATA;


CREATE USER ORDPLUGINS
  IDENTIFIED BY VALUES 'S:E61EC10175AD7A875A0257FC2C1C599C8A608BB28412187DFD26EB40B87E;88A2B2C183431F00'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;


CREATE USER ORDSYS
  IDENTIFIED BY VALUES 'S:091EECF06A7DAD2B5EAFECB0F5A6040D8604E1B0647C8E45873B92E90655;7EFA02EC7EA6B86F'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 Role for ORDSYS 
  GRANT JAVAUSERPRIV TO ORDSYS;
  ALTER USER ORDSYS DEFAULT ROLE ALL;
  -- 1 System Privilege for ORDSYS 
  GRANT UNLIMITED TABLESPACE TO ORDSYS;
  -- 5 Java Privileges for ORDSYS 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'ORDSYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'getClassLoader'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'ORDSYS'
    ,permission_type   => 'SYS:java.util.logging.LoggingPermission'
    ,permission_name   => 'control'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'ORDSYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.ordim11'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'ORDSYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.oraordim11'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'ORDSYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'accessClassInPackage.com.sun.imageio.plugins.jpeg'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/


CREATE USER OUTLN
  IDENTIFIED BY VALUES 'S:D29E36ED1DCFAA20405CFEDAECB6693D812C48839BE7C9A085BDEEFD441B;4A3BA55E08595C81'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 Role for OUTLN 
  GRANT RESOURCE TO OUTLN;
  ALTER USER OUTLN DEFAULT ROLE ALL;
  -- 3 System Privileges for OUTLN 
  GRANT CREATE SESSION TO OUTLN;
  GRANT EXECUTE ANY PROCEDURE TO OUTLN;
  GRANT UNLIMITED TABLESPACE TO OUTLN;


CREATE USER OWBSYS
  IDENTIFIED BY VALUES 'S:C8EDAECF5F3B52CDAA04CB2BBD9D95691DA5F3AB1D9379E6DBEB5E50FA3A;46FFE7B1869A6388'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 10 Roles for OWBSYS 
  GRANT AQ_ADMINISTRATOR_ROLE TO OWBSYS;
  GRANT AQ_USER_ROLE TO OWBSYS;
  GRANT CONNECT TO OWBSYS WITH ADMIN OPTION;
  GRANT CWM_USER TO OWBSYS WITH ADMIN OPTION;
  GRANT JAVA_ADMIN TO OWBSYS;
  GRANT JAVAUSERPRIV TO OWBSYS;
  GRANT OLAP_USER TO OWBSYS WITH ADMIN OPTION;
  GRANT OWB$CLIENT TO OWBSYS WITH ADMIN OPTION;
  GRANT OWB_DESIGNCENTER_VIEW TO OWBSYS WITH ADMIN OPTION;
  GRANT OWB_USER TO OWBSYS WITH ADMIN OPTION;
  ALTER USER OWBSYS DEFAULT ROLE ALL;
  -- 22 System Privileges for OWBSYS 
  GRANT ALTER SESSION TO OWBSYS WITH ADMIN OPTION;
  GRANT ALTER USER TO OWBSYS;
  GRANT CREATE ANY CONTEXT TO OWBSYS;
  GRANT CREATE ANY TRIGGER TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE DATABASE LINK TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE DIMENSION TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE EXTERNAL JOB TO OWBSYS;
  GRANT CREATE INDEXTYPE TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE JOB TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE MATERIALIZED VIEW TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE PROCEDURE TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE PUBLIC SYNONYM TO OWBSYS;
  GRANT CREATE SEQUENCE TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE SESSION TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE SYNONYM TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE TABLE TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE TRIGGER TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE TYPE TO OWBSYS WITH ADMIN OPTION;
  GRANT CREATE VIEW TO OWBSYS WITH ADMIN OPTION;
  GRANT DROP PUBLIC SYNONYM TO OWBSYS;
  GRANT GLOBAL QUERY REWRITE TO OWBSYS WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO OWBSYS WITH ADMIN OPTION;
  -- 10 Java Privileges for OWBSYS 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'owb/bin/unix/NAStart.sh'
    ,permission_action => 'execute'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'owb/bin/win32/NAStart.bat'
    ,permission_action => 'execute'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'owb/bin/admin/rtrepos.properties'
    ,permission_action => 'read,write'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'OWB/BIN/ADMIN/RTREPOS.PROPERTIES'
    ,permission_action => 'read,write'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'owb/bin/unix/run_service.sh'
    ,permission_action => 'read,execute'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'OWB/BIN/WIN32/RUN_SERVICE.BAT'
    ,permission_action => 'read,execute'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => 'owb/bin/win32/run_service.bat'
    ,permission_action => 'read,execute'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.util.PropertyPermission'
    ,permission_name   => '*'
    ,permission_action => 'read,write'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => '*'
    ,permission_action => 'writeFileDescriptor'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'OWBSYS'
    ,permission_type   => 'SYS:java.net.SocketPermission'
    ,permission_name   => '*'
    ,permission_action => 'connect'
    ,key               => KEYNUM
    );
END;
/


CREATE USER OWBSYS_AUDIT
  IDENTIFIED BY VALUES 'S:52BC75D3F9CBFE874DE06A51BF558E185F1A076B8115F9F778FDA12051E9;3378320729DADFE1'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 System Privileges for OWBSYS_AUDIT 
  GRANT ALTER SESSION TO OWBSYS_AUDIT;
  GRANT CREATE SESSION TO OWBSYS_AUDIT;


CREATE USER SCOTT
  IDENTIFIED BY VALUES 'S:80BABDFFCA65C41C2A447C10E1F77D0BB7A4C95511B6F84DC43FD008D435;F894844C34402B67'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SCOTT 
  GRANT CONNECT TO SCOTT;
  GRANT RESOURCE TO SCOTT;
  ALTER USER SCOTT DEFAULT ROLE ALL;
  -- 1 System Privilege for SCOTT 
  GRANT UNLIMITED TABLESPACE TO SCOTT;


CREATE USER SI_INFORMTN_SCHEMA
  IDENTIFIED BY VALUES 'S:A6F0227AC3CBA93B69743917EC5EE7AEFB9B8169597E83C4B1A108FBC29F;84B8CBCA4D477FA3'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 1 System Privilege for SI_INFORMTN_SCHEMA 
  GRANT UNLIMITED TABLESPACE TO SI_INFORMTN_SCHEMA;


CREATE USER SOLUTION_AGRDEP
  IDENTIFIED BY VALUES 'S:2842171C103D78DEDEBFDD89AAF72C1E07BC493761E965A6A956F8E7BC53;F3C9271C70784968'
  DEFAULT TABLESPACE MED
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_AGRDEP 
  GRANT CONNECT TO SOLUTION_AGRDEP;
  GRANT RESOURCE TO SOLUTION_AGRDEP;
  ALTER USER SOLUTION_AGRDEP DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_AGRDEP 
  GRANT CREATE VIEW TO SOLUTION_AGRDEP;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_AGRDEP;


CREATE USER SOLUTION_APTEKA
  IDENTIFIED BY VALUES 'S:BC51C145C2F1012841C5F176246DF8DCD9643CB846647F82B261C5471B5D;25D0C7D4BEA1C3A7'
  DEFAULT TABLESPACE STOR
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_APTEKA 
  GRANT CONNECT TO SOLUTION_APTEKA;
  GRANT RESOURCE TO SOLUTION_APTEKA;
  ALTER USER SOLUTION_APTEKA DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_APTEKA 
  GRANT CREATE VIEW TO SOLUTION_APTEKA;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_APTEKA;


CREATE USER SOLUTION_ASTERISK
  IDENTIFIED BY VALUES 'S:3D56A813F53B73AB7FB562771362E5D1FD839C7F5167F9D23518357E42EE;6121E6C4EA59CCC9'
  DEFAULT TABLESPACE MED
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 4 System Privileges for SOLUTION_ASTERISK 
  GRANT CREATE ANY SYNONYM TO SOLUTION_ASTERISK;
  GRANT CREATE SESSION TO SOLUTION_ASTERISK;
  GRANT CREATE SYNONYM TO SOLUTION_ASTERISK;
  GRANT CREATE VIEW TO SOLUTION_ASTERISK;
  -- 1 Tablespace Quota for SOLUTION_ASTERISK 
  ALTER USER SOLUTION_ASTERISK QUOTA 100M ON USERS;


CREATE USER SOLUTION_DATA
  IDENTIFIED BY VALUES 'S:3524139D29CAF0778281B483D1EE00F98D831D8C7754C324FE3A083E71A1;150CE979BD863E50'
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_DATA 
  GRANT CONNECT TO SOLUTION_DATA;
  GRANT RESOURCE TO SOLUTION_DATA;
  ALTER USER SOLUTION_DATA DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_DATA 
  GRANT CREATE VIEW TO SOLUTION_DATA;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_DATA;


CREATE USER SOLUTION_DBF
  IDENTIFIED BY VALUES 'S:EB180B185B230416B286B1BC3D500BB9D9996AC3330E825C0560F64F6E82;FDE0300B2F65FE47'
  DEFAULT TABLESPACE TMPTS
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_DBF 
  GRANT CONNECT TO SOLUTION_DBF;
  GRANT RESOURCE TO SOLUTION_DBF;
  ALTER USER SOLUTION_DBF DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_DBF 
  GRANT CREATE VIEW TO SOLUTION_DBF;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_DBF;


CREATE USER SOLUTION_DIAGNOSTIC
  IDENTIFIED BY VALUES 'S:A446F9C82BAC5F9CD6D2C782D34F13F64B1855E53047834505BD2A13BE24;87A595434F3227C0'
  DEFAULT TABLESPACE DIAGNOSTIC
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_DIAGNOSTIC 
  GRANT CONNECT TO SOLUTION_DIAGNOSTIC;
  GRANT RESOURCE TO SOLUTION_DIAGNOSTIC;
  ALTER USER SOLUTION_DIAGNOSTIC DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_DIAGNOSTIC 
  GRANT CREATE VIEW TO SOLUTION_DIAGNOSTIC;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_DIAGNOSTIC;


CREATE USER SOLUTION_DIET
  IDENTIFIED BY VALUES 'S:00F6767888604FB1057643FD8EC0F6F916009BF13FF4490D7F3064C39E6C;14A3E74EF7E879A3'
  DEFAULT TABLESPACE STOR
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_DIET 
  GRANT CONNECT TO SOLUTION_DIET;
  GRANT RESOURCE TO SOLUTION_DIET;
  ALTER USER SOLUTION_DIET DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_DIET 
  GRANT CREATE VIEW TO SOLUTION_DIET;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_DIET;


CREATE USER SOLUTION_EPIC
  IDENTIFIED BY VALUES 'S:5C071AADAD80FCA295EE1815ACBABAF20ABE9EDE80C91E0B52078375A268;A678C7D9C9B940D3'
  DEFAULT TABLESPACE EPIC
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_EPIC 
  GRANT CONNECT TO SOLUTION_EPIC;
  GRANT RESOURCE TO SOLUTION_EPIC;
  ALTER USER SOLUTION_EPIC DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_EPIC 
  GRANT CREATE VIEW TO SOLUTION_EPIC;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_EPIC;


CREATE USER SOLUTION_ER
  IDENTIFIED BY VALUES 'S:7FE428262FEE1F651363D1BFAB7A46BE00FB17393FFCA619CF834C34A63D;95F1EFE1044E4990'
  DEFAULT TABLESPACE MED
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_ER 
  GRANT CONNECT TO SOLUTION_ER;
  GRANT RESOURCE TO SOLUTION_ER;
  ALTER USER SOLUTION_ER DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_ER 
  GRANT CREATE VIEW TO SOLUTION_ER;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_ER;


CREATE USER SOLUTION_FORM
  IDENTIFIED BY VALUES 'S:D382D0A11A804D36A5B1340C2B25F521D55B2D25194AFE4B7CF3D90C9982;B4B48B3A3409E9E5'
  DEFAULT TABLESPACE MED
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_FORM 
  GRANT CONNECT TO SOLUTION_FORM;
  GRANT RESOURCE TO SOLUTION_FORM;
  ALTER USER SOLUTION_FORM DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_FORM 
  GRANT CREATE VIEW TO SOLUTION_FORM;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_FORM;


CREATE USER SOLUTION_KLADR
  IDENTIFIED BY VALUES 'S:A83914650F67BEF1E2A0F9E0E43067C824FC787808A2F0AA84B4CAE2F902;5375328FD72AA250'
  DEFAULT TABLESPACE KLADR
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_KLADR 
  GRANT CONNECT TO SOLUTION_KLADR;
  GRANT RESOURCE TO SOLUTION_KLADR;
  ALTER USER SOLUTION_KLADR DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_KLADR 
  GRANT CREATE VIEW TO SOLUTION_KLADR;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_KLADR;


CREATE USER SOLUTION_LAB
  IDENTIFIED BY VALUES 'S:F7C5AD59A9A2415FDAD99B4148D1785058F20BF5234F2C3C73B36728C358;DF99B05ADC1E7D47'
  DEFAULT TABLESPACE LAB
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_LAB 
  GRANT CONNECT TO SOLUTION_LAB;
  GRANT RESOURCE TO SOLUTION_LAB;
  ALTER USER SOLUTION_LAB DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_LAB 
  GRANT CREATE VIEW TO SOLUTION_LAB;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_LAB;


CREATE USER SOLUTION_LOG
  IDENTIFIED BY VALUES 'S:498FE73A4A89962D3CBFEF64FC8267B5F37C1165698BF5558B9D327EA32C;F008646EFCD0B7A6'
  DEFAULT TABLESPACE LOG
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_LOG 
  GRANT CONNECT TO SOLUTION_LOG;
  GRANT RESOURCE TO SOLUTION_LOG;
  ALTER USER SOLUTION_LOG DEFAULT ROLE ALL;
  -- 3 System Privileges for SOLUTION_LOG 
  GRANT CREATE ANY TRIGGER TO SOLUTION_LOG;
  GRANT CREATE VIEW TO SOLUTION_LOG;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_LOG;


CREATE USER SOLUTION_MED
  IDENTIFIED BY VALUES 'S:9A577A0F976BB3349DE714895454CA4BF1EAB728926CBCAD3B03CBDE1284;7FB6AA6335196DBF'
  DEFAULT TABLESPACE MED
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_MED 
  GRANT CONNECT TO SOLUTION_MED;
  GRANT RESOURCE TO SOLUTION_MED;
  ALTER USER SOLUTION_MED DEFAULT ROLE ALL;
  -- 47 System Privileges for SOLUTION_MED 
  GRANT ADMINISTER SQL MANAGEMENT OBJECT TO SOLUTION_MED;
  GRANT ALTER ANY EDITION TO SOLUTION_MED;
  GRANT ALTER ANY ROLE TO SOLUTION_MED;
  GRANT ALTER ANY SEQUENCE TO SOLUTION_MED;
  GRANT ALTER ANY SQL PROFILE TO SOLUTION_MED;
  GRANT ALTER ANY TABLE TO SOLUTION_MED;
  GRANT ALTER ANY TRIGGER TO SOLUTION_MED;
  GRANT ALTER DATABASE TO SOLUTION_MED;
  GRANT ALTER PROFILE TO SOLUTION_MED;
  GRANT ALTER RESOURCE COST TO SOLUTION_MED;
  GRANT ALTER SESSION TO SOLUTION_MED;
  GRANT ALTER SYSTEM TO SOLUTION_MED;
  GRANT ALTER TABLESPACE TO SOLUTION_MED;
  GRANT ALTER USER TO SOLUTION_MED;
  GRANT CHANGE NOTIFICATION TO SOLUTION_MED;
  GRANT CREATE ANY DIRECTORY TO SOLUTION_MED;
  GRANT CREATE ANY INDEX TO SOLUTION_MED;
  GRANT CREATE ANY JOB TO SOLUTION_MED;
  GRANT CREATE ANY MATERIALIZED VIEW TO SOLUTION_MED;
  GRANT CREATE ANY SQL PROFILE TO SOLUTION_MED;
  GRANT CREATE ANY TRIGGER TO SOLUTION_MED;
  GRANT CREATE DATABASE LINK TO SOLUTION_MED WITH ADMIN OPTION;
  GRANT CREATE EXTERNAL JOB TO SOLUTION_MED;
  GRANT CREATE JOB TO SOLUTION_MED;
  GRANT CREATE PROFILE TO SOLUTION_MED;
  GRANT CREATE PUBLIC SYNONYM TO SOLUTION_MED;
  GRANT CREATE ROLE TO SOLUTION_MED;
  GRANT CREATE SYNONYM TO SOLUTION_MED;
  GRANT CREATE TABLE TO SOLUTION_MED;
  GRANT CREATE TABLESPACE TO SOLUTION_MED;
  GRANT CREATE VIEW TO SOLUTION_MED;
  GRANT DEBUG ANY PROCEDURE TO SOLUTION_MED;
  GRANT DEBUG CONNECT SESSION TO SOLUTION_MED WITH ADMIN OPTION;
  GRANT EXECUTE ANY ASSEMBLY TO SOLUTION_MED;
  GRANT FLASHBACK ANY TABLE TO SOLUTION_MED;
  GRANT FLASHBACK ARCHIVE ADMINISTER TO SOLUTION_MED;
  GRANT GRANT ANY OBJECT PRIVILEGE TO SOLUTION_MED;
  GRANT GRANT ANY PRIVILEGE TO SOLUTION_MED;
  GRANT GRANT ANY ROLE TO SOLUTION_MED;
  GRANT INSERT ANY CUBE DIMENSION TO SOLUTION_MED;
  GRANT INSERT ANY TABLE TO SOLUTION_MED;
  GRANT MANAGE SCHEDULER TO SOLUTION_MED;
  GRANT MANAGE TABLESPACE TO SOLUTION_MED;
  GRANT SELECT ANY TABLE TO SOLUTION_MED;
  GRANT UNDER ANY TABLE TO SOLUTION_MED;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_MED;
  GRANT UPDATE ANY TABLE TO SOLUTION_MED;


CREATE USER SOLUTION_OPK
  IDENTIFIED BY VALUES 'S:A009B9F9D5E19E562DC834E21C18D1066C9520E9816A04283ED67A3E8FC7;9E009FEB6D5DC071'
  DEFAULT TABLESPACE STOR
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_OPK 
  GRANT CONNECT TO SOLUTION_OPK;
  GRANT RESOURCE TO SOLUTION_OPK;
  ALTER USER SOLUTION_OPK DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_OPK 
  GRANT CREATE VIEW TO SOLUTION_OPK;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_OPK;


CREATE USER SOLUTION_PACS
  IDENTIFIED BY VALUES 'S:A667256DB54FD5BA691472916E68D577973378445D9CAF6B21AF0B55DB1D;56A9B6EB7339DF35'
  DEFAULT TABLESPACE PACS
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_PACS 
  GRANT CONNECT TO SOLUTION_PACS;
  GRANT RESOURCE TO SOLUTION_PACS;
  ALTER USER SOLUTION_PACS DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_PACS 
  GRANT CREATE VIEW TO SOLUTION_PACS;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_PACS;


CREATE USER SOLUTION_REAGENT
  IDENTIFIED BY VALUES 'S:22A49FED4215963F208CAEE5A8F0153F2CE58D231F671A51BC16CFBBB821;EE9CE378E1F09A6F'
  DEFAULT TABLESPACE MED
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_REAGENT 
  GRANT CONNECT TO SOLUTION_REAGENT;
  GRANT RESOURCE TO SOLUTION_REAGENT;
  ALTER USER SOLUTION_REAGENT DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_REAGENT 
  GRANT CREATE VIEW TO SOLUTION_REAGENT;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_REAGENT;


CREATE USER SOLUTION_REG
  IDENTIFIED BY VALUES 'S:11563AEFF37C7FEAD8C6A3500FFDED3B6031854786BCA3FFB64EFFD6297F;41DD45BB796E090D'
  DEFAULT TABLESPACE REG
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_REG 
  GRANT CONNECT TO SOLUTION_REG;
  GRANT RESOURCE TO SOLUTION_REG;
  ALTER USER SOLUTION_REG DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_REG 
  GRANT CREATE VIEW TO SOLUTION_REG;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_REG;


CREATE USER SOLUTION_RIGHTS
  IDENTIFIED BY VALUES 'S:EC1A4125AA55805B5AE1AB943ED77FF6CA9AA1F19E582DFA42981A7D7508;0F730D06FA3B2B1B'
  DEFAULT TABLESPACE MED
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 2 Roles for SOLUTION_RIGHTS 
  GRANT CONNECT TO SOLUTION_RIGHTS;
  GRANT RESOURCE TO SOLUTION_RIGHTS;
  ALTER USER SOLUTION_RIGHTS DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_RIGHTS 
  GRANT CREATE VIEW TO SOLUTION_RIGHTS;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_RIGHTS;


CREATE USER SOLUTION_SOI
  IDENTIFIED BY VALUES 'S:DFEF41A3FBB59FDC4BF05CFA29C22058408C4C2543C3AE92315E80A6BB94;53CF6FDAF924788D'
  DEFAULT TABLESPACE SOI
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_SOI 
  GRANT CONNECT TO SOLUTION_SOI;
  GRANT RESOURCE TO SOLUTION_SOI;
  ALTER USER SOLUTION_SOI DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_SOI 
  GRANT CREATE VIEW TO SOLUTION_SOI;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_SOI;


CREATE USER SOLUTION_STORAGE
  IDENTIFIED BY VALUES 'S:BF638B3B1DE368AC65AE72E9C55B64670A366FA332933F856855E5A23E7B;923821E66F9A0152'
  DEFAULT TABLESPACE STOR
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_STORAGE 
  GRANT CONNECT TO SOLUTION_STORAGE;
  GRANT RESOURCE TO SOLUTION_STORAGE;
  ALTER USER SOLUTION_STORAGE DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_STORAGE 
  GRANT CREATE VIEW TO SOLUTION_STORAGE;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_STORAGE;


CREATE USER SOLUTION_STORAGE_BUILD
  IDENTIFIED BY VALUES 'S:628EC694EE1922AC334DA4733098D1DE327968E64B0F99B513CFEC40412A;CD5228405EC0C5BF'
  DEFAULT TABLESPACE STOR
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_STORAGE_BUILD 
  GRANT CONNECT TO SOLUTION_STORAGE_BUILD;
  GRANT RESOURCE TO SOLUTION_STORAGE_BUILD;
  ALTER USER SOLUTION_STORAGE_BUILD DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_STORAGE_BUILD 
  GRANT CREATE VIEW TO SOLUTION_STORAGE_BUILD;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_STORAGE_BUILD;


CREATE USER SOLUTION_TMP
  IDENTIFIED BY VALUES 'S:6D17D48337380BB3CBA880BB150C2216A5101BA0258F2AD376880EC51742;B4EB3EB7DAD0FA48'
  DEFAULT TABLESPACE TMPTS
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_TMP 
  GRANT CONNECT TO SOLUTION_TMP;
  GRANT RESOURCE TO SOLUTION_TMP;
  ALTER USER SOLUTION_TMP DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_TMP 
  GRANT CREATE VIEW TO SOLUTION_TMP;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_TMP;


CREATE USER SOLUTION_VAC
  IDENTIFIED BY VALUES 'S:2C0AF80501B79521968B89A9F126F9BE3C238CC182A6A691C1442B2BED85;460DFE29EA23B440'
  DEFAULT TABLESPACE VAC
  TEMPORARY TABLESPACE TEMP
  PROFILE NOEXPIRE_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for SOLUTION_VAC 
  GRANT CONNECT TO SOLUTION_VAC;
  GRANT RESOURCE TO SOLUTION_VAC;
  ALTER USER SOLUTION_VAC DEFAULT ROLE ALL;
  -- 2 System Privileges for SOLUTION_VAC 
  GRANT CREATE VIEW TO SOLUTION_VAC;
  GRANT UNLIMITED TABLESPACE TO SOLUTION_VAC;


CREATE USER SPATIAL_CSW_ADMIN_USR
  IDENTIFIED BY VALUES 'S:15916750881EA39D0F7192F1DA01B2520D1B38D36A12F246BE62F1FD0CB5;1B290858DD14107E'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 3 Roles for SPATIAL_CSW_ADMIN_USR 
  GRANT CONNECT TO SPATIAL_CSW_ADMIN_USR;
  GRANT RESOURCE TO SPATIAL_CSW_ADMIN_USR;
  GRANT SPATIAL_CSW_ADMIN TO SPATIAL_CSW_ADMIN_USR WITH ADMIN OPTION;
  ALTER USER SPATIAL_CSW_ADMIN_USR DEFAULT ROLE ALL;
  -- 8 System Privileges for SPATIAL_CSW_ADMIN_USR 
  GRANT ALTER ANY ROLE TO SPATIAL_CSW_ADMIN_USR;
  GRANT CREATE ANY DIRECTORY TO SPATIAL_CSW_ADMIN_USR;
  GRANT CREATE LIBRARY TO SPATIAL_CSW_ADMIN_USR;
  GRANT CREATE PROCEDURE TO SPATIAL_CSW_ADMIN_USR;
  GRANT CREATE ROLE TO SPATIAL_CSW_ADMIN_USR;
  GRANT DROP ANY ROLE TO SPATIAL_CSW_ADMIN_USR;
  GRANT GRANT ANY ROLE TO SPATIAL_CSW_ADMIN_USR;
  GRANT UNLIMITED TABLESPACE TO SPATIAL_CSW_ADMIN_USR;


CREATE USER SPATIAL_WFS_ADMIN_USR
  IDENTIFIED BY VALUES 'S:CE86B51DC85B3B64A9CFC13FC29D2FE77FB6D6491352E2E9DE9918B1C9F6;7117215D6BEE6E82'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 3 Roles for SPATIAL_WFS_ADMIN_USR 
  GRANT CONNECT TO SPATIAL_WFS_ADMIN_USR;
  GRANT RESOURCE TO SPATIAL_WFS_ADMIN_USR;
  GRANT SPATIAL_WFS_ADMIN TO SPATIAL_WFS_ADMIN_USR WITH ADMIN OPTION;
  ALTER USER SPATIAL_WFS_ADMIN_USR DEFAULT ROLE ALL;
  -- 8 System Privileges for SPATIAL_WFS_ADMIN_USR 
  GRANT ALTER ANY ROLE TO SPATIAL_WFS_ADMIN_USR;
  GRANT CREATE ANY DIRECTORY TO SPATIAL_WFS_ADMIN_USR;
  GRANT CREATE LIBRARY TO SPATIAL_WFS_ADMIN_USR;
  GRANT CREATE PROCEDURE TO SPATIAL_WFS_ADMIN_USR;
  GRANT CREATE ROLE TO SPATIAL_WFS_ADMIN_USR;
  GRANT DROP ANY ROLE TO SPATIAL_WFS_ADMIN_USR;
  GRANT GRANT ANY ROLE TO SPATIAL_WFS_ADMIN_USR;
  GRANT UNLIMITED TABLESPACE TO SPATIAL_WFS_ADMIN_USR;


CREATE USER SYS
  IDENTIFIED BY VALUES 'S:961C5C94927F95CA4616784EF385288314E507850C877932E6ADB69C63ED;8A8F025737A9097A'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 52 Roles for SYS 
  GRANT ADM_PARALLEL_EXECUTE_TASK TO SYS WITH ADMIN OPTION;
  GRANT APEX_ADMINISTRATOR_ROLE TO SYS WITH ADMIN OPTION;
  GRANT AQ_ADMINISTRATOR_ROLE TO SYS WITH ADMIN OPTION;
  GRANT AQ_USER_ROLE TO SYS WITH ADMIN OPTION;
  GRANT AUTHENTICATEDUSER TO SYS WITH ADMIN OPTION;
  GRANT CONNECT TO SYS WITH ADMIN OPTION;
  GRANT CSW_USR_ROLE TO SYS WITH ADMIN OPTION;
  GRANT CTXAPP TO SYS WITH ADMIN OPTION;
  GRANT CWM_USER TO SYS WITH ADMIN OPTION;
  GRANT DATAPUMP_EXP_FULL_DATABASE TO SYS WITH ADMIN OPTION;
  GRANT DATAPUMP_IMP_FULL_DATABASE TO SYS WITH ADMIN OPTION;
  GRANT DBA TO SYS WITH ADMIN OPTION;
  GRANT DBFS_ROLE TO SYS WITH ADMIN OPTION;
  GRANT DELETE_CATALOG_ROLE TO SYS WITH ADMIN OPTION;
  GRANT EJBCLIENT TO SYS WITH ADMIN OPTION;
  GRANT EXECUTE_CATALOG_ROLE TO SYS WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO SYS WITH ADMIN OPTION;
  GRANT GATHER_SYSTEM_STATISTICS TO SYS WITH ADMIN OPTION;
  GRANT HS_ADMIN_EXECUTE_ROLE TO SYS WITH ADMIN OPTION;
  GRANT HS_ADMIN_ROLE TO SYS WITH ADMIN OPTION;
  GRANT HS_ADMIN_SELECT_ROLE TO SYS WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO SYS WITH ADMIN OPTION;
  GRANT JAVA_ADMIN TO SYS WITH ADMIN OPTION;
  GRANT JAVADEBUGPRIV TO SYS WITH ADMIN OPTION;
  GRANT JAVA_DEPLOY TO SYS WITH ADMIN OPTION;
  GRANT JAVAIDPRIV TO SYS WITH ADMIN OPTION;
  GRANT JAVASYSPRIV TO SYS WITH ADMIN OPTION;
  GRANT JAVAUSERPRIV TO SYS WITH ADMIN OPTION;
  GRANT JMXSERVER TO SYS WITH ADMIN OPTION;
  GRANT LOGSTDBY_ADMINISTRATOR TO SYS WITH ADMIN OPTION;
  GRANT MGMT_USER TO SYS WITH ADMIN OPTION;
  GRANT OEM_ADVISOR TO SYS WITH ADMIN OPTION;
  GRANT OEM_MONITOR TO SYS WITH ADMIN OPTION;
  GRANT OLAP_DBA TO SYS WITH ADMIN OPTION;
  GRANT OLAP_USER TO SYS WITH ADMIN OPTION;
  GRANT OLAP_XS_ADMIN TO SYS WITH ADMIN OPTION;
  GRANT ORDADMIN TO SYS WITH ADMIN OPTION;
  GRANT OWB$CLIENT TO SYS WITH ADMIN OPTION;
  GRANT OWB_DESIGNCENTER_VIEW TO SYS WITH ADMIN OPTION;
  GRANT OWB_USER TO SYS WITH ADMIN OPTION;
  GRANT RECOVERY_CATALOG_OWNER TO SYS WITH ADMIN OPTION;
  GRANT RESOURCE TO SYS WITH ADMIN OPTION;
  GRANT SCHEDULER_ADMIN TO SYS WITH ADMIN OPTION;
  GRANT SELECT_CATALOG_ROLE TO SYS WITH ADMIN OPTION;
  GRANT SPATIAL_CSW_ADMIN TO SYS WITH ADMIN OPTION;
  GRANT SPATIAL_WFS_ADMIN TO SYS WITH ADMIN OPTION;
  GRANT WFS_USR_ROLE TO SYS WITH ADMIN OPTION;
  GRANT XDBADMIN TO SYS WITH ADMIN OPTION;
  GRANT XDB_SET_INVOKER TO SYS WITH ADMIN OPTION;
  GRANT XDB_WEBSERVICES TO SYS WITH ADMIN OPTION;
  GRANT XDB_WEBSERVICES_OVER_HTTP TO SYS WITH ADMIN OPTION;
  GRANT XDB_WEBSERVICES_WITH_PUBLIC TO SYS WITH ADMIN OPTION;
  ALTER USER SYS DEFAULT ROLE ALL;
  -- 200 System Privileges for SYS 
  GRANT ADMINISTER ANY SQL TUNING SET TO SYS;
  GRANT ADMINISTER DATABASE TRIGGER TO SYS;
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'SYS', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
  GRANT ADMINISTER SQL MANAGEMENT OBJECT TO SYS;
  GRANT ADMINISTER SQL TUNING SET TO SYS;
  GRANT ADVISOR TO SYS;
  GRANT ALTER ANY ASSEMBLY TO SYS;
  GRANT ALTER ANY CLUSTER TO SYS;
  GRANT ALTER ANY CUBE TO SYS;
  GRANT ALTER ANY CUBE DIMENSION TO SYS;
  GRANT ALTER ANY DIMENSION TO SYS;
  GRANT ALTER ANY EDITION TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT ALTER ANY INDEX TO SYS;
  GRANT ALTER ANY INDEXTYPE TO SYS;
  GRANT ALTER ANY LIBRARY TO SYS;
  GRANT ALTER ANY MATERIALIZED VIEW TO SYS;
  GRANT ALTER ANY MINING MODEL TO SYS;
  GRANT ALTER ANY OPERATOR TO SYS;
  GRANT ALTER ANY OUTLINE TO SYS;
  GRANT ALTER ANY PROCEDURE TO SYS;
  GRANT ALTER ANY ROLE TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT ALTER ANY SEQUENCE TO SYS;
  GRANT ALTER ANY SQL PROFILE TO SYS;
  GRANT ALTER ANY TABLE TO SYS;
  GRANT ALTER ANY TRIGGER TO SYS;
  GRANT ALTER ANY TYPE TO SYS;
  GRANT ALTER DATABASE TO SYS;
  GRANT ALTER PROFILE TO SYS;
  GRANT ALTER RESOURCE COST TO SYS;
  GRANT ALTER ROLLBACK SEGMENT TO SYS;
  GRANT ALTER SESSION TO SYS;
  GRANT ALTER SYSTEM TO SYS;
  GRANT ALTER TABLESPACE TO SYS;
  GRANT ALTER USER TO SYS;
  GRANT ANALYZE ANY TO SYS;
  GRANT AUDIT ANY TO SYS;
  GRANT AUDIT SYSTEM TO SYS;
  GRANT BACKUP ANY TABLE TO SYS;
  GRANT BECOME USER TO SYS;
  GRANT CHANGE NOTIFICATION TO SYS;
  GRANT COMMENT ANY MINING MODEL TO SYS;
  GRANT COMMENT ANY TABLE TO SYS;
  GRANT CREATE ANY ASSEMBLY TO SYS;
  GRANT CREATE ANY CLUSTER TO SYS;
  GRANT CREATE ANY CONTEXT TO SYS;
  GRANT CREATE ANY CUBE TO SYS;
  GRANT CREATE ANY CUBE BUILD PROCESS TO SYS;
  GRANT CREATE ANY CUBE DIMENSION TO SYS;
  GRANT CREATE ANY DIMENSION TO SYS;
  GRANT CREATE ANY DIRECTORY TO SYS;
  GRANT CREATE ANY EDITION TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE ANY INDEX TO SYS;
  GRANT CREATE ANY INDEXTYPE TO SYS;
  GRANT CREATE ANY JOB TO SYS;
  GRANT CREATE ANY LIBRARY TO SYS;
  GRANT CREATE ANY MATERIALIZED VIEW TO SYS;
  GRANT CREATE ANY MEASURE FOLDER TO SYS;
  GRANT CREATE ANY MINING MODEL TO SYS;
  GRANT CREATE ANY OPERATOR TO SYS;
  GRANT CREATE ANY OUTLINE TO SYS;
  GRANT CREATE ANY PROCEDURE TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE ANY SEQUENCE TO SYS;
  GRANT CREATE ANY SQL PROFILE TO SYS;
  GRANT CREATE ANY SYNONYM TO SYS;
  GRANT CREATE ANY TABLE TO SYS;
  GRANT CREATE ANY TRIGGER TO SYS;
  GRANT CREATE ANY TYPE TO SYS;
  GRANT CREATE ANY VIEW TO SYS;
  GRANT CREATE ASSEMBLY TO SYS;
  GRANT CREATE CLUSTER TO SYS;
  GRANT CREATE CUBE TO SYS;
  GRANT CREATE CUBE BUILD PROCESS TO SYS;
  GRANT CREATE CUBE DIMENSION TO SYS;
  GRANT CREATE DATABASE LINK TO SYS;
  GRANT CREATE DIMENSION TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE EXTERNAL JOB TO SYS;
  GRANT CREATE INDEXTYPE TO SYS;
  GRANT CREATE JOB TO SYS;
  GRANT CREATE LIBRARY TO SYS;
  GRANT CREATE MATERIALIZED VIEW TO SYS;
  GRANT CREATE MEASURE FOLDER TO SYS;
  GRANT CREATE MINING MODEL TO SYS;
  GRANT CREATE OPERATOR TO SYS;
  GRANT CREATE PROCEDURE TO SYS;
  GRANT CREATE PROFILE TO SYS;
  GRANT CREATE PUBLIC DATABASE LINK TO SYS;
  GRANT CREATE PUBLIC SYNONYM TO SYS;
  GRANT CREATE ROLE TO SYS;
  GRANT CREATE ROLLBACK SEGMENT TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE SEQUENCE TO SYS;
  GRANT CREATE SESSION TO SYS;
  GRANT CREATE SYNONYM TO SYS;
  GRANT CREATE TABLE TO SYS;
  GRANT CREATE TABLESPACE TO SYS;
  GRANT CREATE TRIGGER TO SYS;
  GRANT CREATE TYPE TO SYS;
  GRANT CREATE USER TO SYS;
  GRANT CREATE VIEW TO SYS;
  GRANT DEBUG ANY PROCEDURE TO SYS;
  GRANT DEBUG CONNECT SESSION TO SYS;
  GRANT DELETE ANY CUBE DIMENSION TO SYS;
  GRANT DELETE ANY MEASURE FOLDER TO SYS;
  GRANT DELETE ANY TABLE TO SYS WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'SYS',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT DROP ANY ASSEMBLY TO SYS;
  GRANT DROP ANY CLUSTER TO SYS;
  GRANT DROP ANY CONTEXT TO SYS;
  GRANT DROP ANY CUBE TO SYS;
  GRANT DROP ANY CUBE BUILD PROCESS TO SYS;
  GRANT DROP ANY CUBE DIMENSION TO SYS;
  GRANT DROP ANY DIMENSION TO SYS;
  GRANT DROP ANY DIRECTORY TO SYS;
  GRANT DROP ANY EDITION TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DROP ANY INDEX TO SYS;
  GRANT DROP ANY INDEXTYPE TO SYS;
  GRANT DROP ANY LIBRARY TO SYS;
  GRANT DROP ANY MATERIALIZED VIEW TO SYS;
  GRANT DROP ANY MEASURE FOLDER TO SYS;
  GRANT DROP ANY MINING MODEL TO SYS;
  GRANT DROP ANY OPERATOR TO SYS;
  GRANT DROP ANY OUTLINE TO SYS;
  GRANT DROP ANY PROCEDURE TO SYS;
  GRANT DROP ANY ROLE TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DROP ANY SEQUENCE TO SYS;
  GRANT DROP ANY SQL PROFILE TO SYS;
  GRANT DROP ANY SYNONYM TO SYS;
  GRANT DROP ANY TABLE TO SYS;
  GRANT DROP ANY TRIGGER TO SYS;
  GRANT DROP ANY TYPE TO SYS;
  GRANT DROP ANY VIEW TO SYS;
  GRANT DROP PROFILE TO SYS;
  GRANT DROP PUBLIC DATABASE LINK TO SYS;
  GRANT DROP PUBLIC SYNONYM TO SYS;
  GRANT DROP ROLLBACK SEGMENT TO SYS;
  GRANT DROP TABLESPACE TO SYS;
  GRANT DROP USER TO SYS;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'SYS',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT EXECUTE ANY ASSEMBLY TO SYS;
  GRANT EXECUTE ANY CLASS TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT EXECUTE ANY INDEXTYPE TO SYS;
  GRANT EXECUTE ANY LIBRARY TO SYS;
  GRANT EXECUTE ANY OPERATOR TO SYS;
  GRANT EXECUTE ANY PROCEDURE TO SYS;
  GRANT EXECUTE ANY PROGRAM TO SYS;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'SYS',
  GRANT_OPTION => TRUE);
END;
/
  GRANT EXECUTE ANY TYPE TO SYS;
  GRANT EXECUTE ASSEMBLY TO SYS;
  GRANT EXPORT FULL DATABASE TO SYS;
  GRANT FLASHBACK ANY TABLE TO SYS;
  GRANT FLASHBACK ARCHIVE ADMINISTER TO SYS;
  GRANT FORCE ANY TRANSACTION TO SYS;
  GRANT FORCE TRANSACTION TO SYS;
  GRANT GLOBAL QUERY REWRITE TO SYS;
  GRANT GRANT ANY OBJECT PRIVILEGE TO SYS;
  GRANT GRANT ANY PRIVILEGE TO SYS;
  GRANT GRANT ANY ROLE TO SYS;
  GRANT IMPORT FULL DATABASE TO SYS;
  GRANT INSERT ANY CUBE DIMENSION TO SYS;
  GRANT INSERT ANY MEASURE FOLDER TO SYS;
  GRANT INSERT ANY TABLE TO SYS WITH ADMIN OPTION;
  GRANT LOCK ANY TABLE TO SYS;
  GRANT MANAGE ANY FILE GROUP TO SYS;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'SYS',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT MANAGE FILE GROUP TO SYS;
  GRANT MANAGE SCHEDULER TO SYS;
  GRANT MANAGE TABLESPACE TO SYS;
  GRANT MERGE ANY VIEW TO SYS;
  GRANT ON COMMIT REFRESH TO SYS;
  GRANT QUERY REWRITE TO SYS;
  GRANT READ ANY FILE GROUP TO SYS;
  GRANT RESTRICTED SESSION TO SYS;
  GRANT RESUMABLE TO SYS;
  GRANT SELECT ANY CUBE TO SYS;
  GRANT SELECT ANY CUBE DIMENSION TO SYS;
  GRANT SELECT ANY MINING MODEL TO SYS;
  GRANT SELECT ANY SEQUENCE TO SYS;
  GRANT SELECT ANY TABLE TO SYS WITH ADMIN OPTION;
  GRANT SELECT ANY TRANSACTION TO SYS;
  GRANT UNDER ANY TABLE TO SYS;
  GRANT UNDER ANY TYPE TO SYS;
  GRANT UNDER ANY VIEW TO SYS;
  GRANT UNLIMITED TABLESPACE TO SYS;
  GRANT UPDATE ANY CUBE TO SYS;
  GRANT UPDATE ANY CUBE BUILD PROCESS TO SYS;
  GRANT UPDATE ANY CUBE DIMENSION TO SYS;
  GRANT UPDATE ANY TABLE TO SYS WITH ADMIN OPTION;
  -- 29 Java Privileges for SYS 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'createClassLoader'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_POLICY_PERMISSION(
     grantee           => 'SYS'
    ,permission_schema => 'SYS'
    ,permission_type   => 'oracle.aurora.rdbms.security.PolicyTablePermission'
    ,permission_name   => '0:oracle.aurora.rdbms.security.PolicyTablePermission#*'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.net.NetPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.security.SecurityPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.net.ssl.SSLPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.util.PropertyPermission'
    ,permission_name   => '*'
    ,permission_action => 'write'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.reflect.ReflectPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.security.AllPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.xaNative'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.corejava'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.jox10oraawt'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.oraioser'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.corejava_d'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'loadLibrary.orajaas'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.security.JServerPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.security.JServerPermission'
    ,permission_name   => 'LoadClassInPackage.java.*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.security.JServerPermission'
    ,permission_name   => 'LoadClassInPackage.oracle.aurora.*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.security.JServerPermission'
    ,permission_name   => 'LoadClassInPackage.oracle.jdbc.*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:java.util.logging.LoggingPermission'
    ,permission_name   => 'control'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.security.auth.AuthPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.management.MBeanServerPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.management.MBeanTrustPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.management.ManagementPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.management.MBeanPermission'
    ,permission_name   => '*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:javax.security.auth.kerberos.ServicePermission'
    ,permission_name   => '*'
    ,permission_action => 'accept,initiate'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYS'
    ,permission_type   => 'SYS:oracle.aurora.rdbms.HandlePermission'
    ,permission_name   => '*'
    ,permission_action => '*'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_POLICY_PERMISSION(
     grantee           => 'SYS'
    ,permission_schema => 'SYS'
    ,permission_type   => 'oracle.aurora.rdbms.security.PolicyTablePermission'
    ,permission_name   => '0:java.lang.RuntimePermission#loadLibrary.ordim11'
    ,key               => KEYNUM
    );
  SYS.DBMS_JAVA.DISABLE_PERMISSION
    (key => KEYNUM);
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_POLICY_PERMISSION(
     grantee           => 'SYS'
    ,permission_schema => 'SYS'
    ,permission_type   => 'oracle.aurora.rdbms.security.PolicyTablePermission'
    ,permission_name   => '0:java.lang.RuntimePermission#loadLibrary.oraordim11'
    ,key               => KEYNUM
    );
  SYS.DBMS_JAVA.DISABLE_PERMISSION
    (key => KEYNUM);
END;
/


CREATE USER SYSMAN
  IDENTIFIED BY VALUES 'S:55257590B951242FDE95EEE2AE7005EFDB818846AB55C8A1F909829EF60F;2CA614501F09FCCC'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;
  -- 3 Roles for SYSMAN 
  GRANT MGMT_USER TO SYSMAN WITH ADMIN OPTION;
  GRANT RESOURCE TO SYSMAN;
  GRANT SELECT_CATALOG_ROLE TO SYSMAN WITH ADMIN OPTION;
  ALTER USER SYSMAN DEFAULT ROLE ALL;
  -- 7 System Privileges for SYSMAN 
  GRANT ALTER SESSION TO SYSMAN;
  GRANT ALTER USER TO SYSMAN;
  GRANT CREATE PUBLIC SYNONYM TO SYSMAN;
  GRANT CREATE TABLE TO SYSMAN;
  GRANT CREATE VIEW TO SYSMAN;
  GRANT SELECT ANY DICTIONARY TO SYSMAN;
  GRANT UNLIMITED TABLESPACE TO SYSMAN;
  -- 1 Tablespace Quota for SYSMAN 
  ALTER USER SYSMAN QUOTA UNLIMITED ON SYSAUX;


CREATE USER SYSTEM
  IDENTIFIED BY VALUES 'S:12B0F75DD3932C2AAB883DAF9849FD9177FDD535A2AFAC1011D8F8055C11;2D594E86F93B17A1'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;
  -- 3 Roles for SYSTEM 
  GRANT AQ_ADMINISTRATOR_ROLE TO SYSTEM WITH ADMIN OPTION;
  GRANT DBA TO SYSTEM WITH ADMIN OPTION;
  GRANT MGMT_USER TO SYSTEM;
  ALTER USER SYSTEM DEFAULT ROLE ALL;
  -- 5 System Privileges for SYSTEM 
  GRANT CREATE MATERIALIZED VIEW TO SYSTEM;
  GRANT CREATE TABLE TO SYSTEM;
  GRANT GLOBAL QUERY REWRITE TO SYSTEM;
  GRANT SELECT ANY TABLE TO SYSTEM;
  GRANT UNLIMITED TABLESPACE TO SYSTEM WITH ADMIN OPTION;
  -- 1 Java Privilege for SYSTEM 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'SYSTEM'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => '<<ALL FILES>>'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
END;
/
  -- 1 Resoure Group Privilege for SYSTEM 
BEGIN
  SYS.DBMS_RESOURCE_MANAGER.clear_pending_area();
  SYS.DBMS_RESOURCE_MANAGER.create_pending_area();
  SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SWITCH_CONSUMER_GROUP
    ('SYSTEM','SYS_GROUP',FALSE);
  SYS.DBMS_RESOURCE_MANAGER.submit_pending_area();
END;
/
BEGIN
  SYS.DBMS_RESOURCE_MANAGER.SET_INITIAL_CONSUMER_GROUP
    ('SYSTEM','SYS_GROUP');
END;
/


CREATE USER WMSYS
  IDENTIFIED BY VALUES 'S:D95A87D61CFBA1BC6926AC8AAE80C879C132D51E96F41E7F6D1650D65272;7C9BA362F8314299'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 3 Roles for WMSYS 
  GRANT CONNECT TO WMSYS;
  GRANT RESOURCE TO WMSYS;
  GRANT WM_ADMIN_ROLE TO WMSYS WITH ADMIN OPTION;
  ALTER USER WMSYS DEFAULT ROLE ALL;
  -- 30 System Privileges for WMSYS 
  GRANT ADMINISTER DATABASE TRIGGER TO WMSYS;
  GRANT ALTER ANY INDEX TO WMSYS;
  GRANT ALTER ANY PROCEDURE TO WMSYS;
  GRANT ALTER ANY TABLE TO WMSYS;
  GRANT ALTER ANY TRIGGER TO WMSYS;
  GRANT ALTER SESSION TO WMSYS;
  GRANT ALTER USER TO WMSYS;
  GRANT CREATE ANY INDEX TO WMSYS;
  GRANT CREATE ANY PROCEDURE TO WMSYS;
  GRANT CREATE ANY TABLE TO WMSYS;
  GRANT CREATE ANY TRIGGER TO WMSYS;
  GRANT CREATE ANY VIEW TO WMSYS;
  GRANT CREATE PUBLIC SYNONYM TO WMSYS;
  GRANT CREATE ROLE TO WMSYS;
  GRANT CREATE SEQUENCE TO WMSYS;
  GRANT DELETE ANY TABLE TO WMSYS;
  GRANT DROP ANY INDEX TO WMSYS;
  GRANT DROP ANY PROCEDURE TO WMSYS;
  GRANT DROP ANY TABLE TO WMSYS;
  GRANT DROP ANY TRIGGER TO WMSYS;
  GRANT DROP ANY VIEW TO WMSYS;
  GRANT DROP PUBLIC SYNONYM TO WMSYS;
  GRANT EXECUTE ANY PROCEDURE TO WMSYS;
  GRANT EXECUTE ANY TYPE TO WMSYS;
  GRANT INSERT ANY TABLE TO WMSYS;
  GRANT LOCK ANY TABLE TO WMSYS;
  GRANT SELECT ANY DICTIONARY TO WMSYS WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO WMSYS;
  GRANT UNLIMITED TABLESPACE TO WMSYS;
  GRANT UPDATE ANY TABLE TO WMSYS;


CREATE USER XDB
  IDENTIFIED BY VALUES 'S:FD74236FC18F44AD0AA1A133069424EC7F3EAF6F30171FBE8B2779E8D0A4;88D8364765FCE6AF'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;
  -- 3 Roles for XDB 
  GRANT CTXAPP TO XDB;
  GRANT JAVAUSERPRIV TO XDB;
  GRANT RESOURCE TO XDB;
  ALTER USER XDB DEFAULT ROLE ALL;
  -- 10 System Privileges for XDB 
  GRANT ALTER SESSION TO XDB;
  GRANT CREATE INDEXTYPE TO XDB;
  GRANT CREATE LIBRARY TO XDB;
  GRANT CREATE OPERATOR TO XDB;
  GRANT CREATE PUBLIC SYNONYM TO XDB;
  GRANT CREATE SESSION TO XDB;
  GRANT CREATE VIEW TO XDB;
  GRANT DROP PUBLIC SYNONYM TO XDB;
  GRANT QUERY REWRITE TO XDB;
  GRANT UNLIMITED TABLESPACE TO XDB;


CREATE USER XS$NULL
  IDENTIFIED BY VALUES 'S:000000000000000000000000000000000000000000000000000000000000'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT LOCK;